import type { CountryOption } from "./types";

/**
 * List of countries with dial codes.
 * Common countries (US, UK, CA, AU) are at the top for quick access.
 */
export const countries: CountryOption[] = [
  // Most common - at top for quick access
  { code: "+1", country: "United States", iso: "US", flag: "🇺🇸" },
  { code: "+1", country: "Canada", iso: "CA", flag: "🇨🇦" },
  { code: "+44", country: "United Kingdom", iso: "GB", flag: "🇬🇧" },
  { code: "+61", country: "Australia", iso: "AU", flag: "🇦🇺" },

  // Alphabetical
  { code: "+93", country: "Afghanistan", iso: "AF", flag: "🇦🇫" },
  { code: "+355", country: "Albania", iso: "AL", flag: "🇦🇱" },
  { code: "+213", country: "Algeria", iso: "DZ", flag: "🇩🇿" },
  { code: "+376", country: "Andorra", iso: "AD", flag: "🇦🇩" },
  { code: "+244", country: "Angola", iso: "AO", flag: "🇦🇴" },
  { code: "+54", country: "Argentina", iso: "AR", flag: "🇦🇷" },
  { code: "+374", country: "Armenia", iso: "AM", flag: "🇦🇲" },
  { code: "+43", country: "Austria", iso: "AT", flag: "🇦🇹" },
  { code: "+994", country: "Azerbaijan", iso: "AZ", flag: "🇦🇿" },
  { code: "+973", country: "Bahrain", iso: "BH", flag: "🇧🇭" },
  { code: "+880", country: "Bangladesh", iso: "BD", flag: "🇧🇩" },
  { code: "+375", country: "Belarus", iso: "BY", flag: "🇧🇾" },
  { code: "+32", country: "Belgium", iso: "BE", flag: "🇧🇪" },
  { code: "+501", country: "Belize", iso: "BZ", flag: "🇧🇿" },
  { code: "+229", country: "Benin", iso: "BJ", flag: "🇧🇯" },
  { code: "+975", country: "Bhutan", iso: "BT", flag: "🇧🇹" },
  { code: "+591", country: "Bolivia", iso: "BO", flag: "🇧🇴" },
  { code: "+387", country: "Bosnia and Herzegovina", iso: "BA", flag: "🇧🇦" },
  { code: "+267", country: "Botswana", iso: "BW", flag: "🇧🇼" },
  { code: "+55", country: "Brazil", iso: "BR", flag: "🇧🇷" },
  { code: "+673", country: "Brunei", iso: "BN", flag: "🇧🇳" },
  { code: "+359", country: "Bulgaria", iso: "BG", flag: "🇧🇬" },
  { code: "+226", country: "Burkina Faso", iso: "BF", flag: "🇧🇫" },
  { code: "+257", country: "Burundi", iso: "BI", flag: "🇧🇮" },
  { code: "+855", country: "Cambodia", iso: "KH", flag: "🇰🇭" },
  { code: "+237", country: "Cameroon", iso: "CM", flag: "🇨🇲" },
  { code: "+238", country: "Cape Verde", iso: "CV", flag: "🇨🇻" },
  { code: "+236", country: "Central African Republic", iso: "CF", flag: "🇨🇫" },
  { code: "+235", country: "Chad", iso: "TD", flag: "🇹🇩" },
  { code: "+56", country: "Chile", iso: "CL", flag: "🇨🇱" },
  { code: "+86", country: "China", iso: "CN", flag: "🇨🇳" },
  { code: "+57", country: "Colombia", iso: "CO", flag: "🇨🇴" },
  { code: "+269", country: "Comoros", iso: "KM", flag: "🇰🇲" },
  { code: "+242", country: "Congo", iso: "CG", flag: "🇨🇬" },
  { code: "+506", country: "Costa Rica", iso: "CR", flag: "🇨🇷" },
  { code: "+385", country: "Croatia", iso: "HR", flag: "🇭🇷" },
  { code: "+53", country: "Cuba", iso: "CU", flag: "🇨🇺" },
  { code: "+357", country: "Cyprus", iso: "CY", flag: "🇨🇾" },
  { code: "+420", country: "Czech Republic", iso: "CZ", flag: "🇨🇿" },
  { code: "+45", country: "Denmark", iso: "DK", flag: "🇩🇰" },
  { code: "+253", country: "Djibouti", iso: "DJ", flag: "🇩🇯" },
  { code: "+593", country: "Ecuador", iso: "EC", flag: "🇪🇨" },
  { code: "+20", country: "Egypt", iso: "EG", flag: "🇪🇬" },
  { code: "+503", country: "El Salvador", iso: "SV", flag: "🇸🇻" },
  { code: "+240", country: "Equatorial Guinea", iso: "GQ", flag: "🇬🇶" },
  { code: "+291", country: "Eritrea", iso: "ER", flag: "🇪🇷" },
  { code: "+372", country: "Estonia", iso: "EE", flag: "🇪🇪" },
  { code: "+251", country: "Ethiopia", iso: "ET", flag: "🇪🇹" },
  { code: "+679", country: "Fiji", iso: "FJ", flag: "🇫🇯" },
  { code: "+358", country: "Finland", iso: "FI", flag: "🇫🇮" },
  { code: "+33", country: "France", iso: "FR", flag: "🇫🇷" },
  { code: "+241", country: "Gabon", iso: "GA", flag: "🇬🇦" },
  { code: "+220", country: "Gambia", iso: "GM", flag: "🇬🇲" },
  { code: "+995", country: "Georgia", iso: "GE", flag: "🇬🇪" },
  { code: "+49", country: "Germany", iso: "DE", flag: "🇩🇪" },
  { code: "+233", country: "Ghana", iso: "GH", flag: "🇬🇭" },
  { code: "+30", country: "Greece", iso: "GR", flag: "🇬🇷" },
  { code: "+502", country: "Guatemala", iso: "GT", flag: "🇬🇹" },
  { code: "+224", country: "Guinea", iso: "GN", flag: "🇬🇳" },
  { code: "+245", country: "Guinea-Bissau", iso: "GW", flag: "🇬🇼" },
  { code: "+592", country: "Guyana", iso: "GY", flag: "🇬🇾" },
  { code: "+509", country: "Haiti", iso: "HT", flag: "🇭🇹" },
  { code: "+504", country: "Honduras", iso: "HN", flag: "🇭🇳" },
  { code: "+852", country: "Hong Kong", iso: "HK", flag: "🇭🇰" },
  { code: "+36", country: "Hungary", iso: "HU", flag: "🇭🇺" },
  { code: "+354", country: "Iceland", iso: "IS", flag: "🇮🇸" },
  { code: "+91", country: "India", iso: "IN", flag: "🇮🇳" },
  { code: "+62", country: "Indonesia", iso: "ID", flag: "🇮🇩" },
  { code: "+98", country: "Iran", iso: "IR", flag: "🇮🇷" },
  { code: "+964", country: "Iraq", iso: "IQ", flag: "🇮🇶" },
  { code: "+353", country: "Ireland", iso: "IE", flag: "🇮🇪" },
  { code: "+972", country: "Israel", iso: "IL", flag: "🇮🇱" },
  { code: "+39", country: "Italy", iso: "IT", flag: "🇮🇹" },
  { code: "+225", country: "Ivory Coast", iso: "CI", flag: "🇨🇮" },
  { code: "+81", country: "Japan", iso: "JP", flag: "🇯🇵" },
  { code: "+962", country: "Jordan", iso: "JO", flag: "🇯🇴" },
  { code: "+7", country: "Kazakhstan", iso: "KZ", flag: "🇰🇿" },
  { code: "+254", country: "Kenya", iso: "KE", flag: "🇰🇪" },
  { code: "+965", country: "Kuwait", iso: "KW", flag: "🇰🇼" },
  { code: "+996", country: "Kyrgyzstan", iso: "KG", flag: "🇰🇬" },
  { code: "+856", country: "Laos", iso: "LA", flag: "🇱🇦" },
  { code: "+371", country: "Latvia", iso: "LV", flag: "🇱🇻" },
  { code: "+961", country: "Lebanon", iso: "LB", flag: "🇱🇧" },
  { code: "+266", country: "Lesotho", iso: "LS", flag: "🇱🇸" },
  { code: "+231", country: "Liberia", iso: "LR", flag: "🇱🇷" },
  { code: "+218", country: "Libya", iso: "LY", flag: "🇱🇾" },
  { code: "+423", country: "Liechtenstein", iso: "LI", flag: "🇱🇮" },
  { code: "+370", country: "Lithuania", iso: "LT", flag: "🇱🇹" },
  { code: "+352", country: "Luxembourg", iso: "LU", flag: "🇱🇺" },
  { code: "+853", country: "Macau", iso: "MO", flag: "🇲🇴" },
  { code: "+389", country: "North Macedonia", iso: "MK", flag: "🇲🇰" },
  { code: "+261", country: "Madagascar", iso: "MG", flag: "🇲🇬" },
  { code: "+265", country: "Malawi", iso: "MW", flag: "🇲🇼" },
  { code: "+60", country: "Malaysia", iso: "MY", flag: "🇲🇾" },
  { code: "+960", country: "Maldives", iso: "MV", flag: "🇲🇻" },
  { code: "+223", country: "Mali", iso: "ML", flag: "🇲🇱" },
  { code: "+356", country: "Malta", iso: "MT", flag: "🇲🇹" },
  { code: "+222", country: "Mauritania", iso: "MR", flag: "🇲🇷" },
  { code: "+230", country: "Mauritius", iso: "MU", flag: "🇲🇺" },
  { code: "+52", country: "Mexico", iso: "MX", flag: "🇲🇽" },
  { code: "+373", country: "Moldova", iso: "MD", flag: "🇲🇩" },
  { code: "+377", country: "Monaco", iso: "MC", flag: "🇲🇨" },
  { code: "+976", country: "Mongolia", iso: "MN", flag: "🇲🇳" },
  { code: "+382", country: "Montenegro", iso: "ME", flag: "🇲🇪" },
  { code: "+212", country: "Morocco", iso: "MA", flag: "🇲🇦" },
  { code: "+258", country: "Mozambique", iso: "MZ", flag: "🇲🇿" },
  { code: "+95", country: "Myanmar", iso: "MM", flag: "🇲🇲" },
  { code: "+264", country: "Namibia", iso: "NA", flag: "🇳🇦" },
  { code: "+977", country: "Nepal", iso: "NP", flag: "🇳🇵" },
  { code: "+31", country: "Netherlands", iso: "NL", flag: "🇳🇱" },
  { code: "+64", country: "New Zealand", iso: "NZ", flag: "🇳🇿" },
  { code: "+505", country: "Nicaragua", iso: "NI", flag: "🇳🇮" },
  { code: "+227", country: "Niger", iso: "NE", flag: "🇳🇪" },
  { code: "+234", country: "Nigeria", iso: "NG", flag: "🇳🇬" },
  { code: "+850", country: "North Korea", iso: "KP", flag: "🇰🇵" },
  { code: "+47", country: "Norway", iso: "NO", flag: "🇳🇴" },
  { code: "+968", country: "Oman", iso: "OM", flag: "🇴🇲" },
  { code: "+92", country: "Pakistan", iso: "PK", flag: "🇵🇰" },
  { code: "+970", country: "Palestine", iso: "PS", flag: "🇵🇸" },
  { code: "+507", country: "Panama", iso: "PA", flag: "🇵🇦" },
  { code: "+675", country: "Papua New Guinea", iso: "PG", flag: "🇵🇬" },
  { code: "+595", country: "Paraguay", iso: "PY", flag: "🇵🇾" },
  { code: "+51", country: "Peru", iso: "PE", flag: "🇵🇪" },
  { code: "+63", country: "Philippines", iso: "PH", flag: "🇵🇭" },
  { code: "+48", country: "Poland", iso: "PL", flag: "🇵🇱" },
  { code: "+351", country: "Portugal", iso: "PT", flag: "🇵🇹" },
  { code: "+974", country: "Qatar", iso: "QA", flag: "🇶🇦" },
  { code: "+40", country: "Romania", iso: "RO", flag: "🇷🇴" },
  { code: "+7", country: "Russia", iso: "RU", flag: "🇷🇺" },
  { code: "+250", country: "Rwanda", iso: "RW", flag: "🇷🇼" },
  { code: "+966", country: "Saudi Arabia", iso: "SA", flag: "🇸🇦" },
  { code: "+221", country: "Senegal", iso: "SN", flag: "🇸🇳" },
  { code: "+381", country: "Serbia", iso: "RS", flag: "🇷🇸" },
  { code: "+65", country: "Singapore", iso: "SG", flag: "🇸🇬" },
  { code: "+421", country: "Slovakia", iso: "SK", flag: "🇸🇰" },
  { code: "+386", country: "Slovenia", iso: "SI", flag: "🇸🇮" },
  { code: "+252", country: "Somalia", iso: "SO", flag: "🇸🇴" },
  { code: "+27", country: "South Africa", iso: "ZA", flag: "🇿🇦" },
  { code: "+82", country: "South Korea", iso: "KR", flag: "🇰🇷" },
  { code: "+211", country: "South Sudan", iso: "SS", flag: "🇸🇸" },
  { code: "+34", country: "Spain", iso: "ES", flag: "🇪🇸" },
  { code: "+94", country: "Sri Lanka", iso: "LK", flag: "🇱🇰" },
  { code: "+249", country: "Sudan", iso: "SD", flag: "🇸🇩" },
  { code: "+597", country: "Suriname", iso: "SR", flag: "🇸🇷" },
  { code: "+46", country: "Sweden", iso: "SE", flag: "🇸🇪" },
  { code: "+41", country: "Switzerland", iso: "CH", flag: "🇨🇭" },
  { code: "+963", country: "Syria", iso: "SY", flag: "🇸🇾" },
  { code: "+886", country: "Taiwan", iso: "TW", flag: "🇹🇼" },
  { code: "+992", country: "Tajikistan", iso: "TJ", flag: "🇹🇯" },
  { code: "+255", country: "Tanzania", iso: "TZ", flag: "🇹🇿" },
  { code: "+66", country: "Thailand", iso: "TH", flag: "🇹🇭" },
  { code: "+228", country: "Togo", iso: "TG", flag: "🇹🇬" },
  { code: "+676", country: "Tonga", iso: "TO", flag: "🇹🇴" },
  { code: "+216", country: "Tunisia", iso: "TN", flag: "🇹🇳" },
  { code: "+90", country: "Turkey", iso: "TR", flag: "🇹🇷" },
  { code: "+993", country: "Turkmenistan", iso: "TM", flag: "🇹🇲" },
  { code: "+256", country: "Uganda", iso: "UG", flag: "🇺🇬" },
  { code: "+380", country: "Ukraine", iso: "UA", flag: "🇺🇦" },
  { code: "+971", country: "United Arab Emirates", iso: "AE", flag: "🇦🇪" },
  { code: "+598", country: "Uruguay", iso: "UY", flag: "🇺🇾" },
  { code: "+998", country: "Uzbekistan", iso: "UZ", flag: "🇺🇿" },
  { code: "+58", country: "Venezuela", iso: "VE", flag: "🇻🇪" },
  { code: "+84", country: "Vietnam", iso: "VN", flag: "🇻🇳" },
  { code: "+967", country: "Yemen", iso: "YE", flag: "🇾🇪" },
  { code: "+260", country: "Zambia", iso: "ZM", flag: "🇿🇲" },
  { code: "+263", country: "Zimbabwe", iso: "ZW", flag: "🇿🇼" },
];

/**
 * Find a country by its dial code.
 * Returns the first match (e.g., +1 returns US before Canada).
 */
export function findCountryByCode(dialCode: string): CountryOption | undefined {
  return countries.find((c) => c.code === dialCode);
}

/**
 * Find a country by its ISO code.
 */
export function findCountryByIso(iso: string): CountryOption | undefined {
  return countries.find((c) => c.iso === iso);
}
